package com.dejie.hospital.registration.mapper;

import com.dejie.hospital.registration.model.Hospital;
import com.dejie.hospital.registration.model.HospitalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface HospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    long countByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    int deleteByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    int deleteByPrimaryKey(Integer hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    int insert(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    int insertSelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    List<Hospital> selectByExampleWithRowbounds(HospitalExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    List<Hospital> selectByExample(HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    Hospital selectByPrimaryKey(Integer hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    int updateByExample(@Param("record") Hospital record, @Param("example") HospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    int updateByPrimaryKeySelective(Hospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    int updateByPrimaryKey(Hospital record);
    List<Hospital> selectAll();
}