package com.dejie.hospital.registration.mapper;

import com.dejie.hospital.registration.model.Level;
import com.dejie.hospital.registration.model.LevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    long countByExample(LevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    int deleteByExample(LevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    int insert(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    int insertSelective(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    List<Level> selectByExampleWithRowbounds(LevelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    List<Level> selectByExample(LevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    Level selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    int updateByExampleSelective(@Param("record") Level record, @Param("example") LevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    int updateByExample(@Param("record") Level record, @Param("example") LevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    int updateByPrimaryKeySelective(Level record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    int updateByPrimaryKey(Level record);
}