package com.dejie.hospital.registration.mapper;

import com.dejie.hospital.registration.model.Shiftapply;
import com.dejie.hospital.registration.model.ShiftapplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ShiftapplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    long countByExample(ShiftapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    int deleteByExample(ShiftapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    int insert(Shiftapply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    int insertSelective(Shiftapply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    List<Shiftapply> selectByExampleWithRowbounds(ShiftapplyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    List<Shiftapply> selectByExample(ShiftapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    Shiftapply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") Shiftapply record, @Param("example") ShiftapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    int updateByExample(@Param("record") Shiftapply record, @Param("example") ShiftapplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    int updateByPrimaryKeySelective(Shiftapply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiftapply
     *
     * @mbg.generated Thu Apr 08 11:08:30 CST 2021
     */
    int updateByPrimaryKey(Shiftapply record);
}