package com.dejie.hospital.registration.model;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.Dpmtid
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private Integer dpmtid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.Dpmtname
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String dpmtname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.Dpmtinfo
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String dpmtinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.Dpmtid
     *
     * @return the value of department.Dpmtid
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Integer getDpmtid() {
        return dpmtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.Dpmtid
     *
     * @param dpmtid the value for department.Dpmtid
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setDpmtid(Integer dpmtid) {
        this.dpmtid = dpmtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.Dpmtname
     *
     * @return the value of department.Dpmtname
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getDpmtname() {
        return dpmtname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.Dpmtname
     *
     * @param dpmtname the value for department.Dpmtname
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setDpmtname(String dpmtname) {
        this.dpmtname = dpmtname == null ? null : dpmtname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.Dpmtinfo
     *
     * @return the value of department.Dpmtinfo
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getDpmtinfo() {
        return dpmtinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.Dpmtinfo
     *
     * @param dpmtinfo the value for department.Dpmtinfo
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setDpmtinfo(String dpmtinfo) {
        this.dpmtinfo = dpmtinfo == null ? null : dpmtinfo.trim();
    }
}