package com.dejie.hospital.registration.model;

import java.util.ArrayList;
import java.util.List;

public class DepartmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public DepartmentExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDpmtidIsNull() {
            addCriterion("Dpmtid is null");
            return (Criteria) this;
        }

        public Criteria andDpmtidIsNotNull() {
            addCriterion("Dpmtid is not null");
            return (Criteria) this;
        }

        public Criteria andDpmtidEqualTo(Integer value) {
            addCriterion("Dpmtid =", value, "dpmtid");
            return (Criteria) this;
        }

        public Criteria andDpmtidNotEqualTo(Integer value) {
            addCriterion("Dpmtid <>", value, "dpmtid");
            return (Criteria) this;
        }

        public Criteria andDpmtidGreaterThan(Integer value) {
            addCriterion("Dpmtid >", value, "dpmtid");
            return (Criteria) this;
        }

        public Criteria andDpmtidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Dpmtid >=", value, "dpmtid");
            return (Criteria) this;
        }

        public Criteria andDpmtidLessThan(Integer value) {
            addCriterion("Dpmtid <", value, "dpmtid");
            return (Criteria) this;
        }

        public Criteria andDpmtidLessThanOrEqualTo(Integer value) {
            addCriterion("Dpmtid <=", value, "dpmtid");
            return (Criteria) this;
        }

        public Criteria andDpmtidIn(List<Integer> values) {
            addCriterion("Dpmtid in", values, "dpmtid");
            return (Criteria) this;
        }

        public Criteria andDpmtidNotIn(List<Integer> values) {
            addCriterion("Dpmtid not in", values, "dpmtid");
            return (Criteria) this;
        }

        public Criteria andDpmtidBetween(Integer value1, Integer value2) {
            addCriterion("Dpmtid between", value1, value2, "dpmtid");
            return (Criteria) this;
        }

        public Criteria andDpmtidNotBetween(Integer value1, Integer value2) {
            addCriterion("Dpmtid not between", value1, value2, "dpmtid");
            return (Criteria) this;
        }

        public Criteria andDpmtnameIsNull() {
            addCriterion("Dpmtname is null");
            return (Criteria) this;
        }

        public Criteria andDpmtnameIsNotNull() {
            addCriterion("Dpmtname is not null");
            return (Criteria) this;
        }

        public Criteria andDpmtnameEqualTo(String value) {
            addCriterion("Dpmtname =", value, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtnameNotEqualTo(String value) {
            addCriterion("Dpmtname <>", value, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtnameGreaterThan(String value) {
            addCriterion("Dpmtname >", value, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtnameGreaterThanOrEqualTo(String value) {
            addCriterion("Dpmtname >=", value, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtnameLessThan(String value) {
            addCriterion("Dpmtname <", value, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtnameLessThanOrEqualTo(String value) {
            addCriterion("Dpmtname <=", value, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtnameLike(String value) {
            addCriterion("Dpmtname like", value, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtnameNotLike(String value) {
            addCriterion("Dpmtname not like", value, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtnameIn(List<String> values) {
            addCriterion("Dpmtname in", values, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtnameNotIn(List<String> values) {
            addCriterion("Dpmtname not in", values, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtnameBetween(String value1, String value2) {
            addCriterion("Dpmtname between", value1, value2, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtnameNotBetween(String value1, String value2) {
            addCriterion("Dpmtname not between", value1, value2, "dpmtname");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoIsNull() {
            addCriterion("Dpmtinfo is null");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoIsNotNull() {
            addCriterion("Dpmtinfo is not null");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoEqualTo(String value) {
            addCriterion("Dpmtinfo =", value, "dpmtinfo");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoNotEqualTo(String value) {
            addCriterion("Dpmtinfo <>", value, "dpmtinfo");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoGreaterThan(String value) {
            addCriterion("Dpmtinfo >", value, "dpmtinfo");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoGreaterThanOrEqualTo(String value) {
            addCriterion("Dpmtinfo >=", value, "dpmtinfo");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoLessThan(String value) {
            addCriterion("Dpmtinfo <", value, "dpmtinfo");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoLessThanOrEqualTo(String value) {
            addCriterion("Dpmtinfo <=", value, "dpmtinfo");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoLike(String value) {
            addCriterion("Dpmtinfo like", value, "dpmtinfo");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoNotLike(String value) {
            addCriterion("Dpmtinfo not like", value, "dpmtinfo");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoIn(List<String> values) {
            addCriterion("Dpmtinfo in", values, "dpmtinfo");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoNotIn(List<String> values) {
            addCriterion("Dpmtinfo not in", values, "dpmtinfo");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoBetween(String value1, String value2) {
            addCriterion("Dpmtinfo between", value1, value2, "dpmtinfo");
            return (Criteria) this;
        }

        public Criteria andDpmtinfoNotBetween(String value1, String value2) {
            addCriterion("Dpmtinfo not between", value1, value2, "dpmtinfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table department
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 03 17:40:30 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table department
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}