package com.dejie.hospital.registration.model;

public class Doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.Did
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.Dname
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.Dsex
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private Integer dsex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.Dtel
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String dtel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.Dlevel
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private Integer dlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.hospital_id
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.Dmajor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private Integer dmajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.Dphoto
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String dphoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.Dinfo
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String dinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.password
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.token
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.Did
     *
     * @return the value of doctor.Did
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.Did
     *
     * @param did the value for doctor.Did
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.Dname
     *
     * @return the value of doctor.Dname
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.Dname
     *
     * @param dname the value for doctor.Dname
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.Dsex
     *
     * @return the value of doctor.Dsex
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public Integer getDsex() {
        return dsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.Dsex
     *
     * @param dsex the value for doctor.Dsex
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setDsex(Integer dsex) {
        this.dsex = dsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.Dtel
     *
     * @return the value of doctor.Dtel
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getDtel() {
        return dtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.Dtel
     *
     * @param dtel the value for doctor.Dtel
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setDtel(String dtel) {
        this.dtel = dtel == null ? null : dtel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.Dlevel
     *
     * @return the value of doctor.Dlevel
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public Integer getDlevel() {
        return dlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.Dlevel
     *
     * @param dlevel the value for doctor.Dlevel
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setDlevel(Integer dlevel) {
        this.dlevel = dlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.hospital_id
     *
     * @return the value of doctor.hospital_id
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.hospital_id
     *
     * @param hospitalId the value for doctor.hospital_id
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.Dmajor
     *
     * @return the value of doctor.Dmajor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public Integer getDmajor() {
        return dmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.Dmajor
     *
     * @param dmajor the value for doctor.Dmajor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setDmajor(Integer dmajor) {
        this.dmajor = dmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.Dphoto
     *
     * @return the value of doctor.Dphoto
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getDphoto() {
        return dphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.Dphoto
     *
     * @param dphoto the value for doctor.Dphoto
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setDphoto(String dphoto) {
        this.dphoto = dphoto == null ? null : dphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.Dinfo
     *
     * @return the value of doctor.Dinfo
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getDinfo() {
        return dinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.Dinfo
     *
     * @param dinfo the value for doctor.Dinfo
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setDinfo(String dinfo) {
        this.dinfo = dinfo == null ? null : dinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.password
     *
     * @return the value of doctor.password
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.password
     *
     * @param password the value for doctor.password
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.token
     *
     * @return the value of doctor.token
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.token
     *
     * @param token the value for doctor.token
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}