package com.dejie.hospital.registration.model;

import java.util.ArrayList;
import java.util.List;

public class DoctorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public DoctorExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDidIsNull() {
            addCriterion("Did is null");
            return (Criteria) this;
        }

        public Criteria andDidIsNotNull() {
            addCriterion("Did is not null");
            return (Criteria) this;
        }

        public Criteria andDidEqualTo(Integer value) {
            addCriterion("Did =", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotEqualTo(Integer value) {
            addCriterion("Did <>", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThan(Integer value) {
            addCriterion("Did >", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidGreaterThanOrEqualTo(Integer value) {
            addCriterion("Did >=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThan(Integer value) {
            addCriterion("Did <", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidLessThanOrEqualTo(Integer value) {
            addCriterion("Did <=", value, "did");
            return (Criteria) this;
        }

        public Criteria andDidIn(List<Integer> values) {
            addCriterion("Did in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotIn(List<Integer> values) {
            addCriterion("Did not in", values, "did");
            return (Criteria) this;
        }

        public Criteria andDidBetween(Integer value1, Integer value2) {
            addCriterion("Did between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andDidNotBetween(Integer value1, Integer value2) {
            addCriterion("Did not between", value1, value2, "did");
            return (Criteria) this;
        }

        public Criteria andDnameIsNull() {
            addCriterion("Dname is null");
            return (Criteria) this;
        }

        public Criteria andDnameIsNotNull() {
            addCriterion("Dname is not null");
            return (Criteria) this;
        }

        public Criteria andDnameEqualTo(String value) {
            addCriterion("Dname =", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameNotEqualTo(String value) {
            addCriterion("Dname <>", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameGreaterThan(String value) {
            addCriterion("Dname >", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameGreaterThanOrEqualTo(String value) {
            addCriterion("Dname >=", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameLessThan(String value) {
            addCriterion("Dname <", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameLessThanOrEqualTo(String value) {
            addCriterion("Dname <=", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameLike(String value) {
            addCriterion("Dname like", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameNotLike(String value) {
            addCriterion("Dname not like", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameIn(List<String> values) {
            addCriterion("Dname in", values, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameNotIn(List<String> values) {
            addCriterion("Dname not in", values, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameBetween(String value1, String value2) {
            addCriterion("Dname between", value1, value2, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameNotBetween(String value1, String value2) {
            addCriterion("Dname not between", value1, value2, "dname");
            return (Criteria) this;
        }

        public Criteria andDsexIsNull() {
            addCriterion("Dsex is null");
            return (Criteria) this;
        }

        public Criteria andDsexIsNotNull() {
            addCriterion("Dsex is not null");
            return (Criteria) this;
        }

        public Criteria andDsexEqualTo(Integer value) {
            addCriterion("Dsex =", value, "dsex");
            return (Criteria) this;
        }

        public Criteria andDsexNotEqualTo(Integer value) {
            addCriterion("Dsex <>", value, "dsex");
            return (Criteria) this;
        }

        public Criteria andDsexGreaterThan(Integer value) {
            addCriterion("Dsex >", value, "dsex");
            return (Criteria) this;
        }

        public Criteria andDsexGreaterThanOrEqualTo(Integer value) {
            addCriterion("Dsex >=", value, "dsex");
            return (Criteria) this;
        }

        public Criteria andDsexLessThan(Integer value) {
            addCriterion("Dsex <", value, "dsex");
            return (Criteria) this;
        }

        public Criteria andDsexLessThanOrEqualTo(Integer value) {
            addCriterion("Dsex <=", value, "dsex");
            return (Criteria) this;
        }

        public Criteria andDsexIn(List<Integer> values) {
            addCriterion("Dsex in", values, "dsex");
            return (Criteria) this;
        }

        public Criteria andDsexNotIn(List<Integer> values) {
            addCriterion("Dsex not in", values, "dsex");
            return (Criteria) this;
        }

        public Criteria andDsexBetween(Integer value1, Integer value2) {
            addCriterion("Dsex between", value1, value2, "dsex");
            return (Criteria) this;
        }

        public Criteria andDsexNotBetween(Integer value1, Integer value2) {
            addCriterion("Dsex not between", value1, value2, "dsex");
            return (Criteria) this;
        }

        public Criteria andDtelIsNull() {
            addCriterion("Dtel is null");
            return (Criteria) this;
        }

        public Criteria andDtelIsNotNull() {
            addCriterion("Dtel is not null");
            return (Criteria) this;
        }

        public Criteria andDtelEqualTo(String value) {
            addCriterion("Dtel =", value, "dtel");
            return (Criteria) this;
        }

        public Criteria andDtelNotEqualTo(String value) {
            addCriterion("Dtel <>", value, "dtel");
            return (Criteria) this;
        }

        public Criteria andDtelGreaterThan(String value) {
            addCriterion("Dtel >", value, "dtel");
            return (Criteria) this;
        }

        public Criteria andDtelGreaterThanOrEqualTo(String value) {
            addCriterion("Dtel >=", value, "dtel");
            return (Criteria) this;
        }

        public Criteria andDtelLessThan(String value) {
            addCriterion("Dtel <", value, "dtel");
            return (Criteria) this;
        }

        public Criteria andDtelLessThanOrEqualTo(String value) {
            addCriterion("Dtel <=", value, "dtel");
            return (Criteria) this;
        }

        public Criteria andDtelLike(String value) {
            addCriterion("Dtel like", value, "dtel");
            return (Criteria) this;
        }

        public Criteria andDtelNotLike(String value) {
            addCriterion("Dtel not like", value, "dtel");
            return (Criteria) this;
        }

        public Criteria andDtelIn(List<String> values) {
            addCriterion("Dtel in", values, "dtel");
            return (Criteria) this;
        }

        public Criteria andDtelNotIn(List<String> values) {
            addCriterion("Dtel not in", values, "dtel");
            return (Criteria) this;
        }

        public Criteria andDtelBetween(String value1, String value2) {
            addCriterion("Dtel between", value1, value2, "dtel");
            return (Criteria) this;
        }

        public Criteria andDtelNotBetween(String value1, String value2) {
            addCriterion("Dtel not between", value1, value2, "dtel");
            return (Criteria) this;
        }

        public Criteria andDlevelIsNull() {
            addCriterion("Dlevel is null");
            return (Criteria) this;
        }

        public Criteria andDlevelIsNotNull() {
            addCriterion("Dlevel is not null");
            return (Criteria) this;
        }

        public Criteria andDlevelEqualTo(Integer value) {
            addCriterion("Dlevel =", value, "dlevel");
            return (Criteria) this;
        }

        public Criteria andDlevelNotEqualTo(Integer value) {
            addCriterion("Dlevel <>", value, "dlevel");
            return (Criteria) this;
        }

        public Criteria andDlevelGreaterThan(Integer value) {
            addCriterion("Dlevel >", value, "dlevel");
            return (Criteria) this;
        }

        public Criteria andDlevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("Dlevel >=", value, "dlevel");
            return (Criteria) this;
        }

        public Criteria andDlevelLessThan(Integer value) {
            addCriterion("Dlevel <", value, "dlevel");
            return (Criteria) this;
        }

        public Criteria andDlevelLessThanOrEqualTo(Integer value) {
            addCriterion("Dlevel <=", value, "dlevel");
            return (Criteria) this;
        }

        public Criteria andDlevelIn(List<Integer> values) {
            addCriterion("Dlevel in", values, "dlevel");
            return (Criteria) this;
        }

        public Criteria andDlevelNotIn(List<Integer> values) {
            addCriterion("Dlevel not in", values, "dlevel");
            return (Criteria) this;
        }

        public Criteria andDlevelBetween(Integer value1, Integer value2) {
            addCriterion("Dlevel between", value1, value2, "dlevel");
            return (Criteria) this;
        }

        public Criteria andDlevelNotBetween(Integer value1, Integer value2) {
            addCriterion("Dlevel not between", value1, value2, "dlevel");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIsNull() {
            addCriterion("hospital_id is null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIsNotNull() {
            addCriterion("hospital_id is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdEqualTo(Integer value) {
            addCriterion("hospital_id =", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotEqualTo(Integer value) {
            addCriterion("hospital_id <>", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThan(Integer value) {
            addCriterion("hospital_id >", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hospital_id >=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThan(Integer value) {
            addCriterion("hospital_id <", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThanOrEqualTo(Integer value) {
            addCriterion("hospital_id <=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIn(List<Integer> values) {
            addCriterion("hospital_id in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotIn(List<Integer> values) {
            addCriterion("hospital_id not in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdBetween(Integer value1, Integer value2) {
            addCriterion("hospital_id between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("hospital_id not between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andDmajorIsNull() {
            addCriterion("Dmajor is null");
            return (Criteria) this;
        }

        public Criteria andDmajorIsNotNull() {
            addCriterion("Dmajor is not null");
            return (Criteria) this;
        }

        public Criteria andDmajorEqualTo(Integer value) {
            addCriterion("Dmajor =", value, "dmajor");
            return (Criteria) this;
        }

        public Criteria andDmajorNotEqualTo(Integer value) {
            addCriterion("Dmajor <>", value, "dmajor");
            return (Criteria) this;
        }

        public Criteria andDmajorGreaterThan(Integer value) {
            addCriterion("Dmajor >", value, "dmajor");
            return (Criteria) this;
        }

        public Criteria andDmajorGreaterThanOrEqualTo(Integer value) {
            addCriterion("Dmajor >=", value, "dmajor");
            return (Criteria) this;
        }

        public Criteria andDmajorLessThan(Integer value) {
            addCriterion("Dmajor <", value, "dmajor");
            return (Criteria) this;
        }

        public Criteria andDmajorLessThanOrEqualTo(Integer value) {
            addCriterion("Dmajor <=", value, "dmajor");
            return (Criteria) this;
        }

        public Criteria andDmajorIn(List<Integer> values) {
            addCriterion("Dmajor in", values, "dmajor");
            return (Criteria) this;
        }

        public Criteria andDmajorNotIn(List<Integer> values) {
            addCriterion("Dmajor not in", values, "dmajor");
            return (Criteria) this;
        }

        public Criteria andDmajorBetween(Integer value1, Integer value2) {
            addCriterion("Dmajor between", value1, value2, "dmajor");
            return (Criteria) this;
        }

        public Criteria andDmajorNotBetween(Integer value1, Integer value2) {
            addCriterion("Dmajor not between", value1, value2, "dmajor");
            return (Criteria) this;
        }

        public Criteria andDphotoIsNull() {
            addCriterion("Dphoto is null");
            return (Criteria) this;
        }

        public Criteria andDphotoIsNotNull() {
            addCriterion("Dphoto is not null");
            return (Criteria) this;
        }

        public Criteria andDphotoEqualTo(String value) {
            addCriterion("Dphoto =", value, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDphotoNotEqualTo(String value) {
            addCriterion("Dphoto <>", value, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDphotoGreaterThan(String value) {
            addCriterion("Dphoto >", value, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDphotoGreaterThanOrEqualTo(String value) {
            addCriterion("Dphoto >=", value, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDphotoLessThan(String value) {
            addCriterion("Dphoto <", value, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDphotoLessThanOrEqualTo(String value) {
            addCriterion("Dphoto <=", value, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDphotoLike(String value) {
            addCriterion("Dphoto like", value, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDphotoNotLike(String value) {
            addCriterion("Dphoto not like", value, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDphotoIn(List<String> values) {
            addCriterion("Dphoto in", values, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDphotoNotIn(List<String> values) {
            addCriterion("Dphoto not in", values, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDphotoBetween(String value1, String value2) {
            addCriterion("Dphoto between", value1, value2, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDphotoNotBetween(String value1, String value2) {
            addCriterion("Dphoto not between", value1, value2, "dphoto");
            return (Criteria) this;
        }

        public Criteria andDinfoIsNull() {
            addCriterion("Dinfo is null");
            return (Criteria) this;
        }

        public Criteria andDinfoIsNotNull() {
            addCriterion("Dinfo is not null");
            return (Criteria) this;
        }

        public Criteria andDinfoEqualTo(String value) {
            addCriterion("Dinfo =", value, "dinfo");
            return (Criteria) this;
        }

        public Criteria andDinfoNotEqualTo(String value) {
            addCriterion("Dinfo <>", value, "dinfo");
            return (Criteria) this;
        }

        public Criteria andDinfoGreaterThan(String value) {
            addCriterion("Dinfo >", value, "dinfo");
            return (Criteria) this;
        }

        public Criteria andDinfoGreaterThanOrEqualTo(String value) {
            addCriterion("Dinfo >=", value, "dinfo");
            return (Criteria) this;
        }

        public Criteria andDinfoLessThan(String value) {
            addCriterion("Dinfo <", value, "dinfo");
            return (Criteria) this;
        }

        public Criteria andDinfoLessThanOrEqualTo(String value) {
            addCriterion("Dinfo <=", value, "dinfo");
            return (Criteria) this;
        }

        public Criteria andDinfoLike(String value) {
            addCriterion("Dinfo like", value, "dinfo");
            return (Criteria) this;
        }

        public Criteria andDinfoNotLike(String value) {
            addCriterion("Dinfo not like", value, "dinfo");
            return (Criteria) this;
        }

        public Criteria andDinfoIn(List<String> values) {
            addCriterion("Dinfo in", values, "dinfo");
            return (Criteria) this;
        }

        public Criteria andDinfoNotIn(List<String> values) {
            addCriterion("Dinfo not in", values, "dinfo");
            return (Criteria) this;
        }

        public Criteria andDinfoBetween(String value1, String value2) {
            addCriterion("Dinfo between", value1, value2, "dinfo");
            return (Criteria) this;
        }

        public Criteria andDinfoNotBetween(String value1, String value2) {
            addCriterion("Dinfo not between", value1, value2, "dinfo");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(String value) {
            addCriterion("token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(String value) {
            addCriterion("token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(String value) {
            addCriterion("token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(String value) {
            addCriterion("token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(String value) {
            addCriterion("token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(String value) {
            addCriterion("token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLike(String value) {
            addCriterion("token like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotLike(String value) {
            addCriterion("token not like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<String> values) {
            addCriterion("token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<String> values) {
            addCriterion("token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(String value1, String value2) {
            addCriterion("token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(String value1, String value2) {
            addCriterion("token not between", value1, value2, "token");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 04 21:45:59 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table doctor
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}