package com.dejie.hospital.registration.model;

public class Hospital {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_id
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_name
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String hospitalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_addr
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String hospitalAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_tel
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String hospitalTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_level
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String hospitalLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_major
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String hospitalMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_photo
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String hospitalPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.hospital_info
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String hospitalInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.password
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital.token
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_id
     *
     * @return the value of hospital.hospital_id
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_id
     *
     * @param hospitalId the value for hospital.hospital_id
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_name
     *
     * @return the value of hospital.hospital_name
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_name
     *
     * @param hospitalName the value for hospital.hospital_name
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_addr
     *
     * @return the value of hospital.hospital_addr
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getHospitalAddr() {
        return hospitalAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_addr
     *
     * @param hospitalAddr the value for hospital.hospital_addr
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setHospitalAddr(String hospitalAddr) {
        this.hospitalAddr = hospitalAddr == null ? null : hospitalAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_tel
     *
     * @return the value of hospital.hospital_tel
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getHospitalTel() {
        return hospitalTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_tel
     *
     * @param hospitalTel the value for hospital.hospital_tel
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setHospitalTel(String hospitalTel) {
        this.hospitalTel = hospitalTel == null ? null : hospitalTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_level
     *
     * @return the value of hospital.hospital_level
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getHospitalLevel() {
        return hospitalLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_level
     *
     * @param hospitalLevel the value for hospital.hospital_level
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setHospitalLevel(String hospitalLevel) {
        this.hospitalLevel = hospitalLevel == null ? null : hospitalLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_major
     *
     * @return the value of hospital.hospital_major
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getHospitalMajor() {
        return hospitalMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_major
     *
     * @param hospitalMajor the value for hospital.hospital_major
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setHospitalMajor(String hospitalMajor) {
        this.hospitalMajor = hospitalMajor == null ? null : hospitalMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_photo
     *
     * @return the value of hospital.hospital_photo
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getHospitalPhoto() {
        return hospitalPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_photo
     *
     * @param hospitalPhoto the value for hospital.hospital_photo
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setHospitalPhoto(String hospitalPhoto) {
        this.hospitalPhoto = hospitalPhoto == null ? null : hospitalPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.hospital_info
     *
     * @return the value of hospital.hospital_info
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getHospitalInfo() {
        return hospitalInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.hospital_info
     *
     * @param hospitalInfo the value for hospital.hospital_info
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setHospitalInfo(String hospitalInfo) {
        this.hospitalInfo = hospitalInfo == null ? null : hospitalInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.password
     *
     * @return the value of hospital.password
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.password
     *
     * @param password the value for hospital.password
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital.token
     *
     * @return the value of hospital.token
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital.token
     *
     * @param token the value for hospital.token
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}