package com.dejie.hospital.registration.model;

public class Hospital_department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_department.id
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_department.hospital_id
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hospital_department.Dpmtid
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private Integer dpmtid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_department.id
     *
     * @return the value of hospital_department.id
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_department.id
     *
     * @param id the value for hospital_department.id
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_department.hospital_id
     *
     * @return the value of hospital_department.hospital_id
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_department.hospital_id
     *
     * @param hospitalId the value for hospital_department.hospital_id
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hospital_department.Dpmtid
     *
     * @return the value of hospital_department.Dpmtid
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Integer getDpmtid() {
        return dpmtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hospital_department.Dpmtid
     *
     * @param dpmtid the value for hospital_department.Dpmtid
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setDpmtid(Integer dpmtid) {
        this.dpmtid = dpmtid;
    }
}