package com.dejie.hospital.registration.model;

import java.util.ArrayList;
import java.util.List;

public class HospitalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public HospitalExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHospitalIdIsNull() {
            addCriterion("hospital_id is null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIsNotNull() {
            addCriterion("hospital_id is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalIdEqualTo(Integer value) {
            addCriterion("hospital_id =", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotEqualTo(Integer value) {
            addCriterion("hospital_id <>", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThan(Integer value) {
            addCriterion("hospital_id >", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hospital_id >=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThan(Integer value) {
            addCriterion("hospital_id <", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdLessThanOrEqualTo(Integer value) {
            addCriterion("hospital_id <=", value, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdIn(List<Integer> values) {
            addCriterion("hospital_id in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotIn(List<Integer> values) {
            addCriterion("hospital_id not in", values, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdBetween(Integer value1, Integer value2) {
            addCriterion("hospital_id between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("hospital_id not between", value1, value2, "hospitalId");
            return (Criteria) this;
        }

        public Criteria andHospitalNameIsNull() {
            addCriterion("hospital_name is null");
            return (Criteria) this;
        }

        public Criteria andHospitalNameIsNotNull() {
            addCriterion("hospital_name is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalNameEqualTo(String value) {
            addCriterion("hospital_name =", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotEqualTo(String value) {
            addCriterion("hospital_name <>", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameGreaterThan(String value) {
            addCriterion("hospital_name >", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_name >=", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameLessThan(String value) {
            addCriterion("hospital_name <", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameLessThanOrEqualTo(String value) {
            addCriterion("hospital_name <=", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameLike(String value) {
            addCriterion("hospital_name like", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotLike(String value) {
            addCriterion("hospital_name not like", value, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameIn(List<String> values) {
            addCriterion("hospital_name in", values, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotIn(List<String> values) {
            addCriterion("hospital_name not in", values, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameBetween(String value1, String value2) {
            addCriterion("hospital_name between", value1, value2, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalNameNotBetween(String value1, String value2) {
            addCriterion("hospital_name not between", value1, value2, "hospitalName");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrIsNull() {
            addCriterion("hospital_addr is null");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrIsNotNull() {
            addCriterion("hospital_addr is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrEqualTo(String value) {
            addCriterion("hospital_addr =", value, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrNotEqualTo(String value) {
            addCriterion("hospital_addr <>", value, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrGreaterThan(String value) {
            addCriterion("hospital_addr >", value, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_addr >=", value, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrLessThan(String value) {
            addCriterion("hospital_addr <", value, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrLessThanOrEqualTo(String value) {
            addCriterion("hospital_addr <=", value, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrLike(String value) {
            addCriterion("hospital_addr like", value, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrNotLike(String value) {
            addCriterion("hospital_addr not like", value, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrIn(List<String> values) {
            addCriterion("hospital_addr in", values, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrNotIn(List<String> values) {
            addCriterion("hospital_addr not in", values, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrBetween(String value1, String value2) {
            addCriterion("hospital_addr between", value1, value2, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalAddrNotBetween(String value1, String value2) {
            addCriterion("hospital_addr not between", value1, value2, "hospitalAddr");
            return (Criteria) this;
        }

        public Criteria andHospitalTelIsNull() {
            addCriterion("hospital_tel is null");
            return (Criteria) this;
        }

        public Criteria andHospitalTelIsNotNull() {
            addCriterion("hospital_tel is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalTelEqualTo(String value) {
            addCriterion("hospital_tel =", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelNotEqualTo(String value) {
            addCriterion("hospital_tel <>", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelGreaterThan(String value) {
            addCriterion("hospital_tel >", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_tel >=", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelLessThan(String value) {
            addCriterion("hospital_tel <", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelLessThanOrEqualTo(String value) {
            addCriterion("hospital_tel <=", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelLike(String value) {
            addCriterion("hospital_tel like", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelNotLike(String value) {
            addCriterion("hospital_tel not like", value, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelIn(List<String> values) {
            addCriterion("hospital_tel in", values, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelNotIn(List<String> values) {
            addCriterion("hospital_tel not in", values, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelBetween(String value1, String value2) {
            addCriterion("hospital_tel between", value1, value2, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalTelNotBetween(String value1, String value2) {
            addCriterion("hospital_tel not between", value1, value2, "hospitalTel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelIsNull() {
            addCriterion("hospital_level is null");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelIsNotNull() {
            addCriterion("hospital_level is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelEqualTo(String value) {
            addCriterion("hospital_level =", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNotEqualTo(String value) {
            addCriterion("hospital_level <>", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelGreaterThan(String value) {
            addCriterion("hospital_level >", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_level >=", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelLessThan(String value) {
            addCriterion("hospital_level <", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelLessThanOrEqualTo(String value) {
            addCriterion("hospital_level <=", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelLike(String value) {
            addCriterion("hospital_level like", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNotLike(String value) {
            addCriterion("hospital_level not like", value, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelIn(List<String> values) {
            addCriterion("hospital_level in", values, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNotIn(List<String> values) {
            addCriterion("hospital_level not in", values, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelBetween(String value1, String value2) {
            addCriterion("hospital_level between", value1, value2, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalLevelNotBetween(String value1, String value2) {
            addCriterion("hospital_level not between", value1, value2, "hospitalLevel");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorIsNull() {
            addCriterion("hospital_major is null");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorIsNotNull() {
            addCriterion("hospital_major is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorEqualTo(String value) {
            addCriterion("hospital_major =", value, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorNotEqualTo(String value) {
            addCriterion("hospital_major <>", value, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorGreaterThan(String value) {
            addCriterion("hospital_major >", value, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_major >=", value, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorLessThan(String value) {
            addCriterion("hospital_major <", value, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorLessThanOrEqualTo(String value) {
            addCriterion("hospital_major <=", value, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorLike(String value) {
            addCriterion("hospital_major like", value, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorNotLike(String value) {
            addCriterion("hospital_major not like", value, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorIn(List<String> values) {
            addCriterion("hospital_major in", values, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorNotIn(List<String> values) {
            addCriterion("hospital_major not in", values, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorBetween(String value1, String value2) {
            addCriterion("hospital_major between", value1, value2, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalMajorNotBetween(String value1, String value2) {
            addCriterion("hospital_major not between", value1, value2, "hospitalMajor");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoIsNull() {
            addCriterion("hospital_photo is null");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoIsNotNull() {
            addCriterion("hospital_photo is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoEqualTo(String value) {
            addCriterion("hospital_photo =", value, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoNotEqualTo(String value) {
            addCriterion("hospital_photo <>", value, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoGreaterThan(String value) {
            addCriterion("hospital_photo >", value, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_photo >=", value, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoLessThan(String value) {
            addCriterion("hospital_photo <", value, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoLessThanOrEqualTo(String value) {
            addCriterion("hospital_photo <=", value, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoLike(String value) {
            addCriterion("hospital_photo like", value, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoNotLike(String value) {
            addCriterion("hospital_photo not like", value, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoIn(List<String> values) {
            addCriterion("hospital_photo in", values, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoNotIn(List<String> values) {
            addCriterion("hospital_photo not in", values, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoBetween(String value1, String value2) {
            addCriterion("hospital_photo between", value1, value2, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalPhotoNotBetween(String value1, String value2) {
            addCriterion("hospital_photo not between", value1, value2, "hospitalPhoto");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoIsNull() {
            addCriterion("hospital_info is null");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoIsNotNull() {
            addCriterion("hospital_info is not null");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoEqualTo(String value) {
            addCriterion("hospital_info =", value, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoNotEqualTo(String value) {
            addCriterion("hospital_info <>", value, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoGreaterThan(String value) {
            addCriterion("hospital_info >", value, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoGreaterThanOrEqualTo(String value) {
            addCriterion("hospital_info >=", value, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoLessThan(String value) {
            addCriterion("hospital_info <", value, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoLessThanOrEqualTo(String value) {
            addCriterion("hospital_info <=", value, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoLike(String value) {
            addCriterion("hospital_info like", value, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoNotLike(String value) {
            addCriterion("hospital_info not like", value, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoIn(List<String> values) {
            addCriterion("hospital_info in", values, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoNotIn(List<String> values) {
            addCriterion("hospital_info not in", values, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoBetween(String value1, String value2) {
            addCriterion("hospital_info between", value1, value2, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andHospitalInfoNotBetween(String value1, String value2) {
            addCriterion("hospital_info not between", value1, value2, "hospitalInfo");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(String value) {
            addCriterion("token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(String value) {
            addCriterion("token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(String value) {
            addCriterion("token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(String value) {
            addCriterion("token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(String value) {
            addCriterion("token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(String value) {
            addCriterion("token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLike(String value) {
            addCriterion("token like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotLike(String value) {
            addCriterion("token not like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<String> values) {
            addCriterion("token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<String> values) {
            addCriterion("token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(String value1, String value2) {
            addCriterion("token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(String value1, String value2) {
            addCriterion("token not between", value1, value2, "token");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hospital
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 04 21:45:59 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hospital
     *
     * @mbg.generated Sun Apr 04 21:45:59 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}