package com.dejie.hospital.registration.model;

public class Level {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level.id
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level.Dlevel
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    private Integer dlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level.Lname
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    private String lname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level.fee
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    private String fee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level.id
     *
     * @return the value of level.id
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level.id
     *
     * @param id the value for level.id
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level.Dlevel
     *
     * @return the value of level.Dlevel
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public Integer getDlevel() {
        return dlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level.Dlevel
     *
     * @param dlevel the value for level.Dlevel
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public void setDlevel(Integer dlevel) {
        this.dlevel = dlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level.Lname
     *
     * @return the value of level.Lname
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level.Lname
     *
     * @param lname the value for level.Lname
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public void setLname(String lname) {
        this.lname = lname == null ? null : lname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level.fee
     *
     * @return the value of level.fee
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public String getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level.fee
     *
     * @param fee the value for level.fee
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public void setFee(String fee) {
        this.fee = fee == null ? null : fee.trim();
    }
}