package com.dejie.hospital.registration.model;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Mnumber
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private Integer mnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.username
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.password
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.token
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Mnumber
     *
     * @return the value of manager.Mnumber
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Integer getMnumber() {
        return mnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Mnumber
     *
     * @param mnumber the value for manager.Mnumber
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setMnumber(Integer mnumber) {
        this.mnumber = mnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.username
     *
     * @return the value of manager.username
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.username
     *
     * @param username the value for manager.username
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.password
     *
     * @return the value of manager.password
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.password
     *
     * @param password the value for manager.password
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.token
     *
     * @return the value of manager.token
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.token
     *
     * @param token the value for manager.token
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}