package com.dejie.hospital.registration.model;

public class Notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.noticeid
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private Integer noticeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.title
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.gmt_create
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.gmt_modified
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.creator
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.description
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.noticeid
     *
     * @return the value of notice.noticeid
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Integer getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.noticeid
     *
     * @param noticeid the value for notice.noticeid
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setNoticeid(Integer noticeid) {
        this.noticeid = noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.gmt_create
     *
     * @return the value of notice.gmt_create
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.gmt_create
     *
     * @param gmtCreate the value for notice.gmt_create
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.gmt_modified
     *
     * @return the value of notice.gmt_modified
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.gmt_modified
     *
     * @param gmtModified the value for notice.gmt_modified
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.creator
     *
     * @return the value of notice.creator
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.creator
     *
     * @param creator the value for notice.creator
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.description
     *
     * @return the value of notice.description
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.description
     *
     * @param description the value for notice.description
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}