package com.dejie.hospital.registration.model;

public class Register {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.Rid
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.cardnumber
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    private Integer cardnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.hospital_id
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.Did
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.Dmajor
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    private Integer dmajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.registerDate
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    private Long registerdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.Scid
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    private Integer scid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.visitDate
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    private Long visitdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.Rstatus
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    private Integer rstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.time
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    private Integer time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.Rid
     *
     * @return the value of register.Rid
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.Rid
     *
     * @param rid the value for register.Rid
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.cardnumber
     *
     * @return the value of register.cardnumber
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public Integer getCardnumber() {
        return cardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.cardnumber
     *
     * @param cardnumber the value for register.cardnumber
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public void setCardnumber(Integer cardnumber) {
        this.cardnumber = cardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.hospital_id
     *
     * @return the value of register.hospital_id
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.hospital_id
     *
     * @param hospitalId the value for register.hospital_id
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.Did
     *
     * @return the value of register.Did
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.Did
     *
     * @param did the value for register.Did
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.Dmajor
     *
     * @return the value of register.Dmajor
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public Integer getDmajor() {
        return dmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.Dmajor
     *
     * @param dmajor the value for register.Dmajor
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public void setDmajor(Integer dmajor) {
        this.dmajor = dmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.registerDate
     *
     * @return the value of register.registerDate
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public Long getRegisterdate() {
        return registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.registerDate
     *
     * @param registerdate the value for register.registerDate
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public void setRegisterdate(Long registerdate) {
        this.registerdate = registerdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.Scid
     *
     * @return the value of register.Scid
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public Integer getScid() {
        return scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.Scid
     *
     * @param scid the value for register.Scid
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public void setScid(Integer scid) {
        this.scid = scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.visitDate
     *
     * @return the value of register.visitDate
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public Long getVisitdate() {
        return visitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.visitDate
     *
     * @param visitdate the value for register.visitDate
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public void setVisitdate(Long visitdate) {
        this.visitdate = visitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.Rstatus
     *
     * @return the value of register.Rstatus
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public Integer getRstatus() {
        return rstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.Rstatus
     *
     * @param rstatus the value for register.Rstatus
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public void setRstatus(Integer rstatus) {
        this.rstatus = rstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.time
     *
     * @return the value of register.time
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.time
     *
     * @param time the value for register.time
     *
     * @mbg.generated Tue Mar 30 12:34:23 CST 2021
     */
    public void setTime(Integer time) {
        this.time = time;
    }
}