package com.dejie.hospital.registration.model;

public class Schedule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.Scid
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    private Integer scid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.week
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    private Integer week;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.hospital_id
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    private Integer hospitalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.Did
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.Dmajor
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    private Integer dmajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.register_limited
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    private Integer registerLimited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.time
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    private Integer time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.Scid
     *
     * @return the value of schedule.Scid
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public Integer getScid() {
        return scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.Scid
     *
     * @param scid the value for schedule.Scid
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public void setScid(Integer scid) {
        this.scid = scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.week
     *
     * @return the value of schedule.week
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public Integer getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.week
     *
     * @param week the value for schedule.week
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public void setWeek(Integer week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.hospital_id
     *
     * @return the value of schedule.hospital_id
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.hospital_id
     *
     * @param hospitalId the value for schedule.hospital_id
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.Did
     *
     * @return the value of schedule.Did
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.Did
     *
     * @param did the value for schedule.Did
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.Dmajor
     *
     * @return the value of schedule.Dmajor
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public Integer getDmajor() {
        return dmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.Dmajor
     *
     * @param dmajor the value for schedule.Dmajor
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public void setDmajor(Integer dmajor) {
        this.dmajor = dmajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.register_limited
     *
     * @return the value of schedule.register_limited
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public Integer getRegisterLimited() {
        return registerLimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.register_limited
     *
     * @param registerLimited the value for schedule.register_limited
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public void setRegisterLimited(Integer registerLimited) {
        this.registerLimited = registerLimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.time
     *
     * @return the value of schedule.time
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.time
     *
     * @param time the value for schedule.time
     *
     * @mbg.generated Tue Mar 16 20:26:32 CST 2021
     */
    public void setTime(Integer time) {
        this.time = time;
    }
}