package com.dejie.hospital.registration.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Cardnumber
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private Integer cardnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Idcard
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.truename
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String truename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.token
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    private String token;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Cardnumber
     *
     * @return the value of user.Cardnumber
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public Integer getCardnumber() {
        return cardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Cardnumber
     *
     * @param cardnumber the value for user.Cardnumber
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setCardnumber(Integer cardnumber) {
        this.cardnumber = cardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Idcard
     *
     * @return the value of user.Idcard
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Idcard
     *
     * @param idcard the value for user.Idcard
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.truename
     *
     * @return the value of user.truename
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.truename
     *
     * @param truename the value for user.truename
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setTruename(String truename) {
        this.truename = truename == null ? null : truename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.token
     *
     * @return the value of user.token
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.token
     *
     * @param token the value for user.token
     *
     * @mbg.generated Wed Mar 03 17:40:30 CST 2021
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }
}